# # Specify the base image to use
# FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# WORKDIR /app

# # Copy the project file and restore dependencies
# COPY *.csproj .
# RUN dotnet restore

# # Copy the rest of the application files and build the application
# COPY . .
# RUN dotnet publish -c Release -o out


# # Create the final image for deployment
# FROM mcr.microsoft.com/dotnet/aspnet:6.0
# WORKDIR /app
# COPY --from=build /app/out .

# # Start the application
# ENTRYPOINT ["dotnet", "CompanyManagement.dll"]


FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CompanyManagement.csproj", "./"]
RUN dotnet restore "./CompanyManagement.csproj"
COPY . .
RUN dotnet build "CompanyManagement.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CompanyManagement.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CompanyManagement.dll"]



